### ISSUE TITLE
Fix Report not appearing

### ISSUE THREAD

**Issue by MaximoOliveira** [ali-ghanbari/prf#4]
First of all thank you for creating such a helpful tool!

I followed the instructions given in setup section to install the PRF Maven plugin.

Also followed the instruction from **Example 1: Chart-1 of Defects4J** :

```
cd examples
cd Chart_1_buggy
# Please make sure you have adjusted the POM file as described above
mvn clean test -DskipTests  -Dhttps.protocols=TLSv1.2
mvn edu.utdallas:prf-maven-plugin:run -Dhttps.protocols=TLSv1.2
```

And was able to have a Successful Build, however I don't see the patch that fixes the bug in the fix report.

What I get is the following:
![image](https://user-images.githubusercontent.com/36827697/103921378-be5d9f80-5112-11eb-9e37-b1f0978bec41.png)

Which is different from the fix report that appears in the readme:

![image](https://user-images.githubusercontent.com/36827697/103921553-f1079800-5112-11eb-89d8-4419f32d0b20.png)

I confirmed that after following the instructions, a folder named 'mutated' in examples/Chart_1_buggy/ is created that contains 168 patches.

Is there anything I possibly missed for the fix report to appear empty?

Thank you!

**Comment by ali-ghanbari** [comment]
Hi,

Thank you for your interest in PRF, and thank you for reporting this so that I can fix possible issues with the codebase.

PRF doesn't print any diff in the fix-report because none of the 168 patches generated by CapGen plugin (on your computer) passes the test cases. Since I just followed the instructions and the fix-report appears just fine, I suspect this could be an issue with the environment:

(1) Please confirm that you have SciTools Understand (which is freely available for academic use at https://www.scitools.com/) installed on your computer, because by following the instructions in the README file, you invoke CapGen plugin which expects Understand installed on your system and its `bin` directory be in `PATH`, so that the command `und` is available. 

(2) Please make sure that `JAVA_HOME` points to JDK 1.7 home directory and `javac -version` shows version 1.7.xxxx before applying PRF on Defects4J bugs.

If you still have issues with the fix-report, please kindly let me know. Thanks!

**Comment by MaximoOliveira** [comment]
Thank you Ali

I did not install 'Understand', I'll try to get a license and replicate the same steps!

**Comment by MaximoOliveira** [comment]
Hello again!

**(1)** I've installed 'Understand' and added it to `PATH` and the command `und` is available:
![image](https://user-images.githubusercontent.com/36827697/104454973-8cc75700-559e-11eb-844e-765d0bc6a8ab.png)

(2) 
![image](https://user-images.githubusercontent.com/36827697/104455211-dfa10e80-559e-11eb-956f-e2fdd408b710.png)

The only thing changed from the `pom.xml` file from Chart_1_buggy was the `launcherJDKHomeDirectory`, so it points to jdk8

![image](https://user-images.githubusercontent.com/36827697/104455431-2bec4e80-559f-11eb-9161-956e32bef02f.png)

These changes did not fix the problem with generating a valid patch and hence the fix report still appears empty

Any further suggestions on what I might be missing?

Thank you!

**Comment by ali-ghanbari** [comment]
Hi,

Thanks for letting me know.

I cloned fresh copies of PRF on 4 different machines (three Ubuntu Linux of different versions and one MacOS X).
In one machine, I invoked PRF from IntelliJ IDEA's terminal window (the way you did, I guess), just for good measure (just in case IDEA sets some environment variables or something).
As the screenshots show, I was able to find the plausible patch.

I am emphasizing that I have been using jdk1.7.0_80 as my JDK 1.7 and jdk1.8.0_251 or jdk1.8.0_211 as my JDK 1.8.
I couldn't find the Open JDK that you're using neither was I able to find the specific build of JDK 1.7 that you are using.
I understand that Java is supposed to be _portable_ and there shouldn't be differences between different builds of JDK, but slight peculiarities in the implementation of native libraries can go a long way in making the test cases silently fail.
Sometimes both patch generation plugin and patch validation system are correct but the test cases fail because they depend on environment or they are flaky. Although I cannot put my finger on a specific version of JDK, I am quite sure that JFreeChart tests depend on certain GUI-related libraries and are not compatible with some versions JDK.
Thus, I suggest downloading the aforementioned JDK's from Oracle's website and try again with a fresh copy of PRF (I use Maven a lot, and I have come across rare cases where Maven does not overwrite the JAR file in the local repo. So, I suggest manually deleting already installed PRF copy by `rm -rf ~/.m2/repository/edu/utdallas/prf*` and reinstalling PRF and trying again).

Since the only way that I can solve the problem (in case it is related to the codebase itself) is that I can reproduce the error, if you see the error again please kindly redirect both `stdout` and `stderr` in a text file and upload here. Hopefully, I will be able to solve the problem for you.
BTW, if you face the problem again, please let me know the contents of environment variable `$LD_LIBRARY_PATH` (if it's empty, you should be good).

Thanks!

P.S. Screenshots of the patch diff:

![Screen Shot 2021-01-13 at 7 40 14 PM](https://user-images.githubusercontent.com/30007640/104541597-87422f00-55e7-11eb-83ba-5f05312312b1.png)
![Screen Shot 2021-01-13 at 7 46 23 PM](https://user-images.githubusercontent.com/30007640/104541599-87dac580-55e7-11eb-9256-d91378b7d0c4.png)
![Screen Shot 2021-01-13 at 7 59 37 PM](https://user-images.githubusercontent.com/30007640/104541600-88735c00-55e7-11eb-872b-dff835c88230.png)
![Screen Shot 2021-01-13 at 9 34 26 PM](https://user-images.githubusercontent.com/30007640/104541603-88735c00-55e7-11eb-9ad2-fa91fff97d0b.png)

**Comment by MaximoOliveira** [comment]
Thank you @ali-ghanbari!

I guess it had something to do with the jdk version i had.

I appreciate your help and patience! Have a great day!
